@extends('layouts.base')
@section('title', 'Institutional Yield Farming')

@section('content')
    <!-- Hero Section -->
    <section class="section py-5 mt-5 bg-dark-custom position-relative" style="min-height: 400px; display: flex; align-items: center; overflow: hidden;">
        <div class="position-absolute dot-grid-bg" style="top:0; right:0; width:50%; height:100%; z-index:1; opacity:0.15;"></div>
        <div class="position-absolute" style="background-image: url('{{ asset('images/assets/hero-bg.png') }}'); background-position: right center; background-size: contain; background-repeat: no-repeat; bottom: 0; top: 0; right: 0; width: 50%; z-index: 2; opacity: 0.8;"></div>
        
        <div class="container position-relative" style="z-index:3;">
            <div class="row align-items-center w-100">
                <div class="col-lg-7" data-aos="fade-right">
                    <h1 class="display-4 font-weight-bold mb-4 text-white">Yield Farming</h1>
                    <p class="lead text-muted mb-5 max-width-700">Participate in the liquidity layer of the decentralized web. Provide liquidity to automated market makers (AMMs) and earn a share of trading fees plus governance incentives.</p>
                    <div class="d-flex flex-wrap">
                        <a href="{{ url('/register') }}" class="btn btn-warning text-dark font-weight-bold btn-lg mr-3 px-5 mb-3 shadow-lg">Supply Liquidity</a>
                        <a href="{{ url('/register') }}" class="btn btn-outline-light btn-lg mb-3">View Active Pools</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Farming Overview Section -->
    <section class="section py-5 bg-light-custom position-relative">
        <div class="position-absolute dot-grid-bg" style="top:0; left:0; width:40%; height:100%; z-index:1; opacity:0.15;"></div>
        <div class="container position-relative" style="z-index:2;">
            <div class="row align-items-center mb-5">
                <div class="col-lg-6 order-lg-2 mb-5 mb-lg-0" data-aos="fade-left">
                    <h2 class="mb-4 font-weight-bold text-dark">Automated Liquidity Provision</h2>
                    <p class="text-muted mb-4">Yield Farming is the process of providing liquidity to decentralized protocols in exchange for rewards. By supplying pairs of assets to liquidity pools, you enable decentralized trading and receive a portion of the transaction fees generated by the protocol.</p>
                    <p class="text-muted">Our platform simplifies the complex process of yield farming, offering a curated selection of audited pools with high capital efficiency and managed risk profiles.</p>
                    
                    <div class="p-4 mt-4 shadow-sm rounded border bg-white" style="border-left: 4px solid var(--inst-accent);">
                        <h6 class="font-weight-bold text-dark mb-2">Audit-First Approach</h6>
                        <p class="small text-muted mb-0">We only integrate with protocols that have passed rigorous third-party audits, significantly reducing the risk of smart contract vulnerabilities.</p>
                    </div>
                </div>
                <div class="col-lg-6 order-lg-1" data-aos="fade-right">
                    <div class="p-4 rounded-lg border shadow-lg bg-white">
                        <h5 class="font-weight-bold text-dark mb-4"><i class="mdi mdi-water-percent mr-2 text-warning"></i>Featured Farming Pools</h5>
                        <div class="pool-item mb-4 pb-3 border-bottom">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <span class="font-weight-bold text-dark">USDC / USDT (Stable)</span>
                                <span class="text-success font-weight-bold">12.5% APY</span>
                            </div>
                            <div class="progress" style="height: 6px;">
                                <div class="progress-bar bg-warning" style="width: 85%;"></div>
                            </div>
                        </div>
                        <div class="pool-item mb-4 pb-3 border-bottom">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <span class="font-weight-bold text-dark">ETH / WBTC</span>
                                <span class="text-success font-weight-bold">18.2% APY</span>
                            </div>
                            <div class="progress" style="height: 6px;">
                                <div class="progress-bar bg-warning" style="width: 65%;"></div>
                            </div>
                        </div>
                        <div class="pool-item">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <span class="font-weight-bold text-dark">SOL / USDC</span>
                                <span class="text-success font-weight-bold">24.8% APY</span>
                            </div>
                            <div class="progress" style="height: 6px;">
                                <div class="progress-bar bg-warning" style="width: 45%;"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Farming Features Grid -->
    <section class="section py-5 bg-dark-custom position-relative">
        <div class="position-absolute dot-grid-bg" style="top:0; right:0; width:100%; height:100%; z-index:1; opacity:0.1;"></div>
        <div class="container position-relative" style="z-index:2;">
            <div class="row text-center mb-5">
                <div class="col-12" data-aos="fade-up">
                    <h2 class="font-weight-bold text-white">Why Farm with Us?</h2>
                    <p class="text-muted">Maximized yields, minimized complexity.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 mb-4" data-aos="fade-up" data-aos-delay="100">
                    <div class="p-5 rounded border h-100 shadow-sm" style="background: rgba(255,255,255,0.02); border-color: var(--inst-border) !important;">
                        <i class="mdi mdi-gas-station h1 text-warning mb-4 d-block"></i>
                        <h4 class="text-white font-weight-bold mb-3">Gas-Efficient Batching</h4>
                        <p class="text-muted small">We batch transactions to minimize gas costs, ensuring that even smaller liquidity providers can farm profitably.</p>
                    </div>
                </div>
                <div class="col-md-4 mb-4" data-aos="fade-up" data-aos-delay="200">
                    <div class="p-5 rounded border h-100 shadow-sm" style="background: rgba(255,255,255,0.02); border-color: var(--inst-border) !important;">
                        <i class="mdi mdi-chart-bubble h1 text-warning mb-4 d-block"></i>
                        <h4 class="text-white font-weight-bold mb-3">Impermanent Loss Protection</h4>
                        <p class="text-muted small">Access sophisticated hedging tools and stablecoin-heavy pools to mitigate the impact of impermanent loss.</p>
                    </div>
                </div>
                <div class="col-md-4 mb-4" data-aos="fade-up" data-aos-delay="300">
                    <div class="p-5 rounded border h-100 shadow-sm" style="background: rgba(255,255,255,0.02); border-color: var(--inst-border) !important;">
                        <i class="mdi mdi-cog-transfer h1 text-warning mb-4 d-block"></i>
                        <h4 class="text-white font-weight-bold mb-3">Auto-Compounding</h4>
                        <p class="text-muted small">Our smart contracts automatically harvest and reinvest your rewards to maximize your effective APY.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    @include('home.partials.trade-anywhere')
    @include('home.partials.achievement')
    @include('home.partials.cta')

    <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            AOS.init({
                duration: 800,
                easing: 'ease-out-cubic',
                once: false,
                offset: 50
            });
        });
    </script>
@endsection
